# Generated by Django 4.2.27 on 2026-03-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('contra_entrega', 'Contra entrega'), ('transferencia', 'Transferencia bancaria'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('azul', 'Azul')], max_length=20, null=True),
        ),
    ]
