# Generated by Django 4.2.27 on 2026-07-17 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def guardar_datos_historicos(apps, schema_editor):
    ItemPedido = apps.get_model('carrito', 'ItemPedido')
    for item in ItemPedido.objects.select_related('producto').iterator():
        if not item.producto_id:
            continue
        item.nombre_producto = item.producto.nombre
        item.marca_producto = item.producto.marca
        item.save(update_fields=['nombre_producto', 'marca_producto'])


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_resena_unica_por_usuario_producto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrito', '0006_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='marca_producto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='nombre_producto',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pagado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='referencia_pago',
            field=models.CharField(blank=True, db_index=True, max_length=160),
        ),
        migrations.AddField(
            model_name='pedido',
            name='reserva_expira_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='stock_reintegrado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='stock_reservado',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(guardar_datos_historicos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='itempedido',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TransaccionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(max_length=30)),
                ('referencia', models.CharField(max_length=160, unique=True)),
                ('estado', models.CharField(choices=[('creada', 'Creada'), ('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada')], default='creada', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='USD', max_length=3)),
                ('respuesta', models.JSONField(blank=True, default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='carrito.pedido')),
            ],
        ),
    ]
