# Generated by Django 4.2.27 on 2026-07-17 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0014_producto_slug'),
        ('carrito', '0007_itempedido_marca_producto_itempedido_nombre_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('reserva', 'Reserva por pedido'), ('reintegro', 'Reintegro por cancelacion'), ('ajuste', 'Ajuste manual'), ('entrada', 'Entrada de inventario'), ('salida', 'Salida de inventario')], max_length=20)),
                ('cantidad', models.IntegerField(help_text='Valor positivo para entradas y negativo para salidas.')),
                ('stock_anterior', models.PositiveIntegerField()),
                ('stock_resultante', models.PositiveIntegerField()),
                ('motivo', models.CharField(blank=True, max_length=240)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='carrito.pedido')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='productos.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado', '-id'],
            },
        ),
    ]
