# Generated by Django 4.2.27 on 2026-03-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='perfumes/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('tipo', models.CharField(choices=[('EDT', 'Eau de Toilette'), ('EDP', 'Eau de Parfum'), ('PARFUM', 'Parfum')], max_length=10)),
                ('temporada', models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('day', 'Day'), ('night', 'Night'), ('special', 'Special')], max_length=20)),
                ('tamano_ml', models.PositiveIntegerField()),
                ('notas_salida', models.CharField(blank=True, max_length=255)),
                ('notas_corazon', models.CharField(blank=True, max_length=255)),
                ('notas_fondo', models.CharField(blank=True, max_length=255)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
