# Generated by Django 4.2.27 on 2026-03-17 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_creacion',
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='notas_corazon',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='notas_fondo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='notas_salida',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tamano_ml',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='temporada',
            field=models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('night', 'Night'), ('day', 'Day'), ('special', 'Special')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
