# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_base64',
            field=models.TextField(blank=True, help_text='Imagen guardada en base64 para persistencia', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_nombre',
            field=models.CharField(blank=True, help_text='Nombre original del archivo de imagen', max_length=255, null=True),
        ),
    ]
