# Generated by Django 4.2.27 on 2026-03-18 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0004_resena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='notas_corazon',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='notas_fondo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='notas_salida',
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='temporada',
            field=models.CharField(blank=True, choices=[('summer', 'Summer'), ('winter', 'Winter'), ('night', 'Night'), ('day', 'Day'), ('special', 'Special')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('eau_de_parfum', 'Eau de Parfum'), ('eau_de_toilette', 'Eau de Toilette'), ('eau_de_cologne', 'Eau de Cologne'), ('body_spray', 'Body Spray')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('usuario', 'producto')},
        ),
    ]
