# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
        ('productos', '0005_remove_producto_notas_corazon_and_more'),
        ('productos', '0002_producto_imagen_base64'),
    ]

    operations = [
    ]
