# Generated by Django 4.2.27 on 2026-07-17 13:38

from django.db import migrations, models
from django.utils.text import slugify


def generar_slugs(apps, schema_editor):
    Producto = apps.get_model('productos', 'Producto')
    usados = set()
    for producto in Producto.objects.order_by('id').iterator():
        base = slugify(producto.nombre) or f'producto-{producto.id}'
        slug = base
        numero = 2
        while slug in usados or Producto.objects.exclude(pk=producto.pk).filter(slug=slug).exists():
            slug = f'{base}-{numero}'
            numero += 1
        producto.slug = slug
        producto.save(update_fields=['slug'])
        usados.add(slug)


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0013_resena_unica_por_usuario_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=models.SlugField(blank=True, max_length=230, null=True, unique=True),
        ),
        migrations.RunPython(generar_slugs, migrations.RunPython.noop),
    ]
