version: '3.8'

services:
  db:
    image: postgres:15
    container_name: perfumeria_db
    environment:
      POSTGRES_DB: perfumeria_local
      POSTGRES_USER: perfumeria_user
      POSTGRES_PASSWORD: perfumeria123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
