services:
  # Web Service Python 3.11
  - type: web
    name: perfumeria-darcy
    plan: free
    runtime: python-3.11
    buildCommand: "./build.sh && python manage.py crear_admin"
    startCommand: "gunicorn perfumeria.wsgi:application"
    autoDeploy: true

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: perfumeria.settings_prod
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: perfumeria-db
          property: connectionString
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: true
      - key: EMAIL_HOST_USER
        value: gilbertandeliz04@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: gvwa fiqu giim fyiw
      - key: DEFAULT_FROM_EMAIL
        value: noreply@perfumeria.com
      - key: PAYPAL_MODE
        value: sandbox
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_SECRET
        sync: false

    healthCheckPath: /
    staticDir: staticfiles
    mountPath: /static

  # Database (PostgreSQL)
  - type: pserv
    name: perfumeria-db
    plan: free
    env: postgres

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: perfumeria-db
          property: connectionString