services:
  # Web Service Python 3.12; WhiteNoise sirve los archivos estáticos.
  - type: web
    name: perfumeria-darcy
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python manage.py sync_admin && gunicorn perfumeria.wsgi:application"
    autoDeploy: true

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: perfumeria.settings_prod
      - key: PYTHON_VERSION
        value: 3.12.12
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        value: perfumeria-darcy.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://perfumeria-darcy.onrender.com
      - key: RESEND_API_KEY
        sync: false
      - key: RESEND_FROM_EMAIL
        sync: false
      - key: RESEND_FROM_NAME
        value: D.A.R.C.Y.
      - key: PUBLIC_SITE_URL
        value: https://perfumeria-darcy.onrender.com
      - key: PAYPAL_MODE
        value: sandbox
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_SECRET
        sync: false
      - key: PAYPAL_WEBHOOK_ID
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false

    healthCheckPath: /
